
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'D12B98D64D936A87C019870E594A4889'
    
_lr_action_items = {'FIRSTLINE':([0,],[1,]),'NAME':([0,],[4,]),',':([4,7,10,11,],[5,9,-4,12,]),'.':([6,],[8,]),'INTEGER':([5,8,9,12,],[6,10,6,13,]),'$end':([1,2,3,13,],[-1,0,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[2,]),'float':([5,9,],[7,11,]),'data':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> FIRSTLINE','start',1,'p_start','plysurname.py',30),
  ('start -> data','start',1,'p_start','plysurname.py',31),
  ('data -> NAME , float , float , INTEGER','data',7,'p_data','plysurname.py',39),
  ('float -> INTEGER . INTEGER','float',3,'p_float','plysurname.py',43),
]
